// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kolokwium2poprawa.Data;

#nullable disable

namespace kolokwium2poprawa.Migrations
{
    [DbContext(typeof(myContext))]
    partial class myContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("kolokwium2poprawa.Models.Car", b =>
                {
                    b.Property<int>("IdCar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCar"));

                    b.Property<int>("IdColor")
                        .HasColumnType("int");

                    b.Property<int>("IdModel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PricePerDay")
                        .HasColumnType("int");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.HasKey("IdCar");

                    b.HasIndex("IdColor");

                    b.HasIndex("IdModel");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            IdCar = 1,
                            IdColor = 1,
                            IdModel = 1,
                            Name = "dacia",
                            PricePerDay = 100,
                            Seats = 4,
                            VIN = "gggg"
                        },
                        new
                        {
                            IdCar = 2,
                            IdColor = 1,
                            IdModel = 2,
                            Name = "porche",
                            PricePerDay = 300,
                            Seats = 6,
                            VIN = "vvvv"
                        });
                });

            modelBuilder.Entity("kolokwium2poprawa.Models.Car_Rental", b =>
                {
                    b.Property<int>("IdCar_Rental")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCar_Rental"));

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<int>("Disscount")
                        .HasColumnType("int");

                    b.Property<int>("IdCar")
                        .HasColumnType("int");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.HasKey("IdCar_Rental");

                    b.HasIndex("IdCar");

                    b.HasIndex("IdClient");

                    b.ToTable("CarRentals");

                    b.HasData(
                        new
                        {
                            IdCar_Rental = 1,
                            DateFrom = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTo = new DateTime(2023, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Disscount = 15,
                            IdCar = 1,
                            IdClient = 1,
                            TotalPrice = 1000
                        },
                        new
                        {
                            IdCar_Rental = 2,
                            DateFrom = new DateTime(2022, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTo = new DateTime(2021, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Disscount = 0,
                            IdCar = 2,
                            IdClient = 2,
                            TotalPrice = 500
                        });
                });

            modelBuilder.Entity("kolokwium2poprawa.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClient"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdClient");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            IdClient = 1,
                            Adress = "zzz",
                            FirstName = "Jan",
                            LastName = "Kowalski"
                        },
                        new
                        {
                            IdClient = 2,
                            Adress = "fff",
                            FirstName = "cc",
                            LastName = "pp"
                        });
                });

            modelBuilder.Entity("kolokwium2poprawa.Models.Color", b =>
                {
                    b.Property<int>("IdColor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdColor"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdColor");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            IdColor = 1,
                            Name = "zielony"
                        },
                        new
                        {
                            IdColor = 2,
                            Name = "czerwony"
                        });
                });

            modelBuilder.Entity("kolokwium2poprawa.Models.Model", b =>
                {
                    b.Property<int>("IdModel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModel"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdModel");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            IdModel = 1,
                            Name = "kombi"
                        },
                        new
                        {
                            IdModel = 2,
                            Name = "cos"
                        });
                });

            modelBuilder.Entity("kolokwium2poprawa.Models.Car", b =>
                {
                    b.HasOne("kolokwium2poprawa.Models.Color", "Color")
                        .WithMany("Cars")
                        .HasForeignKey("IdColor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kolokwium2poprawa.Models.Model", "Model")
                        .WithMany("Cars")
                        .HasForeignKey("IdModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("kolokwium2poprawa.Models.Car_Rental", b =>
                {
                    b.HasOne("kolokwium2poprawa.Models.Car", "Car")
                        .WithMany("CarRentals")
                        .HasForeignKey("IdCar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kolokwium2poprawa.Models.Client", "Client")
                        .WithMany("CarRentals")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("kolokwium2poprawa.Models.Car", b =>
                {
                    b.Navigation("CarRentals");
                });

            modelBuilder.Entity("kolokwium2poprawa.Models.Client", b =>
                {
                    b.Navigation("CarRentals");
                });

            modelBuilder.Entity("kolokwium2poprawa.Models.Color", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("kolokwium2poprawa.Models.Model", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
